global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
rule_files:
  - /etc/prometheus/rules.yml
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
  # For running operators in debug mode outside kubernetes
- job_name: operator-debug
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - 10.144.1.175:8081
  # For running the operator within kubernetes in a prod env
- job_name: operator-kubernetes
  scrape_interval: 60s
  kubernetes_sd_configs:
  - role: pod
  relabel_configs:
  - source_labels: [__meta_kubernetes_namespace]
    regex: appuio-k8up-operator
    action: keep
  - source_labels: [__meta_kubernetes_pod_label_app]
    regex: k8up-operator
    action: keep
  - source_labels: [__meta_kubernetes_pod_container_port_number]
    regex:
    action: drop
  - source_labels: [__meta_kubernetes_pod_label_pod_template_hash]
    regex:
    action: drop
