builds:
- main: ./cmd/k8up
  binary: k8up
  env:
  - CGO_ENABLED=0 # this is needed otherwise the Docker image build is faulty
  goarch:
  - amd64
  goos:
  - linux

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-snapshot"

dockers:
- image_templates:
  - "ghcr.io/k8up-io/k8up:v{{ .Version }}"
  - "quay.io/k8up-io/k8up:v{{ .Version }}"

  # For prereleases, updating `latest` and the floating tags of the major
  # version does not make sense. Only the image for the exact version should
  # be pushed.
  - "{{ if not .Prerelease }}ghcr.io/k8up-io/k8up:v{{ .Major }}{{ end }}"
  - "{{ if not .Prerelease }}quay.io/k8up-io/k8up:v{{ .Major }}{{ end }}"

  - "{{ if not .Prerelease }}ghcr.io/k8up-io/k8up:latest{{ end }}"
  - "{{ if not .Prerelease }}quay.io/k8up-io/k8up:latest{{ end }}"

release:
  prerelease: auto
  github:
    owner: vshn
    name: k8up
  extra_files:
  - glob: ./k8up-crd*.yaml
