apiVersion: v1
kind: Secret
metadata:
  name: backup-credentials
type: Opaque
stringData:
  username: minio
  password: minio123

---

apiVersion: v1
kind: Secret
metadata:
  name: backup-repo
type: Opaque
stringData:
  password: p@ssw0rd

