apiVersion: appuio.ch/v1alpha1
kind: Schedule
metadata:
  name: schedule-test

spec:
  backup:
    schedule: '* * * * *'
    keepJobs: 4
    backend:
      s3:
        endpoint: http://10.144.1.224:9000
        bucket: baas
        accessKeyIDSecretRef:
          name: backup-credentials
          key: username
        secretAccessKeySecretRef:
          name: backup-credentials
          key: password
    promURL: http://10.144.1.224:9000
    repoPasswordSecretRef:
      name: backup-repo
      key: password
