= K8up - Kubernetes Backup Operator

image::k8up-logo.svg[]

[discrete]
== Introduction

K8up (pronounced `/keɪtæpp/` or simply "ketchup") is a Kubernetes Operator distributed via a https://github.com/k8up-io/k8up/tree/master/charts/k8up[Helm chart], compatible with https://www.openshift.com/[OpenShift] and plain https://kubernetes.io/[Kubernetes]. It allows cluster operators to:

* Backup all PVCs marked as `ReadWriteMany`, `ReadWriteOnce` or with a specific label.
* Perform individual, on-demand backups.
* Schedule backups to be executed on a regular basis.
* Schedule archivals (for example to AWS Glacier), usually executed in longer intervals.
* Perform "Application Aware" backups, containing the output of any tool capable of writing to `stdout`.
* Check the backup repository for its integrity.
* Prune old backups from a repository.
* Restore backups with the help of the k8up CLI tool.

K8up is:

* Stable and production ready since 2019.
* Based on top of https://restic.readthedocs.io/en/latest/[Restic], it can store backups in any S3-compatible storage, such as Amazon S3 or https://github.com/minio/minio#readme[Minio].
* Written in https://golang.org/[Go].
* A https://www.cncf.io/sandbox-projects/[CNCF Sandbox] Open Source project, https://github.com/k8up-io/k8up[hosted at GitHub].

https://landscape.cncf.io/?item=runtime\--cloud-native-storage\--k8up[image:https://img.shields.io/badge/CNCF%20Landscape-5699C6[CNCF LANDSCAPE]]

TIP: The xref:tutorials/tutorial.adoc[tutorial] gives you a glimpse into K8up. Give it a try!

[discrete]
== Documentation

The documentation is inspired by the https://documentation.divio.com/[Divio's documentation structure]:

Tutorials:: _Learning-oriented_: Simple lessons to learn about K8up.

How-to guides:: _Problem-oriented_: step-by-step guides to achieve a goal.

Technical reference:: _Information-oriented_: explaining the inner ongoings of K8up.

Explanation:: _Understanding-oriented_: puts k8up in context.
