---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: k8up-operator
subjects:
- kind: ServiceAccount
  namespace: myproject
  name: k8up-operator
roleRef:
  kind: ClusterRole
  name: k8up-operator
  apiGroup: rbac.authorization.k8s.io
