---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: k8up
  labels:
    app: k8up
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8up
  template:
    metadata:
      labels:
        app: k8up
    spec:
      containers:
        - name: k8up-operator
          image: 172.30.1.1:5000/myproject/k8up:0.0.1
          imagePullPolicy: Always
          env:
            - name: BACKUP_IMAGE
              value: 172.30.1.1:5000/myproject/wrestic:0.0.1
            - name: BACKUP_GLOBALACCESSKEYID
              value: 8U0UDNYPNUDTUS1LIAF3
            - name: BACKUP_GLOBALSECRETACCESSKEY
              value: ip3cdrkXcHmH4S7if7erKPNoxDn27V0vrg6CHHem
            - name: BACKUP_GLOBALREPOPASSWORD
              value: password
            - name: BACKUP_GLOBALRESTORES3BUCKET
              value: restoremin
            - name: BACKUP_GLOBALRESTORES3ENDPOINT
              value: http://10.144.1.224:9000
            - name: BACKUP_GLOBALRESTORES3ACCESKEYID
              value: 8U0UDNYPNUDTUS1LIAF3
            - name: BACKUP_GLOBALRESTORES3SECRETACCESSKEY
              value: ip3cdrkXcHmH4S7if7erKPNoxDn27V0vrg6CHHem
            - name: BACKUP_GLOBALS3ENDPOINT
              value: http://10.144.1.224:9000
            - name: BACKUP_GLOBALS3BUCKET
              value: k8up
      serviceAccountName: k8up-operator

#kubectl create clusterrolebinding cluster-admin-binding-2   --clusterrole=cluster-admin   --user=system:system:serviceaccount:myproject:default
