/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "git.vshn.net/vshn/baas/apis/backup/v1alpha1"
	scheme "git.vshn.net/vshn/baas/client/k8s/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ArchivesGetter has a method to return a ArchiveInterface.
// A group's client should implement this interface.
type ArchivesGetter interface {
	Archives(namespace string) ArchiveInterface
}

// ArchiveInterface has methods to work with Archive resources.
type ArchiveInterface interface {
	Create(*v1alpha1.Archive) (*v1alpha1.Archive, error)
	Update(*v1alpha1.Archive) (*v1alpha1.Archive, error)
	UpdateStatus(*v1alpha1.Archive) (*v1alpha1.Archive, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.Archive, error)
	List(opts v1.ListOptions) (*v1alpha1.ArchiveList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Archive, err error)
	ArchiveExpansion
}

// archives implements ArchiveInterface
type archives struct {
	client rest.Interface
	ns     string
}

// newArchives returns a Archives
func newArchives(c *AppuioV1alpha1Client, namespace string) *archives {
	return &archives{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the archive, and returns the corresponding archive object, and an error if there is any.
func (c *archives) Get(name string, options v1.GetOptions) (result *v1alpha1.Archive, err error) {
	result = &v1alpha1.Archive{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("archives").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Archives that match those selectors.
func (c *archives) List(opts v1.ListOptions) (result *v1alpha1.ArchiveList, err error) {
	result = &v1alpha1.ArchiveList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("archives").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested archives.
func (c *archives) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("archives").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a archive and creates it.  Returns the server's representation of the archive, and an error, if there is any.
func (c *archives) Create(archive *v1alpha1.Archive) (result *v1alpha1.Archive, err error) {
	result = &v1alpha1.Archive{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("archives").
		Body(archive).
		Do().
		Into(result)
	return
}

// Update takes the representation of a archive and updates it. Returns the server's representation of the archive, and an error, if there is any.
func (c *archives) Update(archive *v1alpha1.Archive) (result *v1alpha1.Archive, err error) {
	result = &v1alpha1.Archive{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("archives").
		Name(archive.Name).
		Body(archive).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *archives) UpdateStatus(archive *v1alpha1.Archive) (result *v1alpha1.Archive, err error) {
	result = &v1alpha1.Archive{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("archives").
		Name(archive.Name).
		SubResource("status").
		Body(archive).
		Do().
		Into(result)
	return
}

// Delete takes name of the archive and deletes it. Returns an error if one occurs.
func (c *archives) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("archives").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *archives) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("archives").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched archive.
func (c *archives) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Archive, err error) {
	result = &v1alpha1.Archive{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("archives").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
