/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/vshn/k8up/apis/backup/v1alpha1"
	scheme "github.com/vshn/k8up/client/k8s/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// PreBackupPodsGetter has a method to return a PreBackupPodInterface.
// A group's client should implement this interface.
type PreBackupPodsGetter interface {
	PreBackupPods(namespace string) PreBackupPodInterface
}

// PreBackupPodInterface has methods to work with PreBackupPod resources.
type PreBackupPodInterface interface {
	Create(*v1alpha1.PreBackupPod) (*v1alpha1.PreBackupPod, error)
	Update(*v1alpha1.PreBackupPod) (*v1alpha1.PreBackupPod, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.PreBackupPod, error)
	List(opts v1.ListOptions) (*v1alpha1.PreBackupPodList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.PreBackupPod, err error)
	PreBackupPodExpansion
}

// preBackupPods implements PreBackupPodInterface
type preBackupPods struct {
	client rest.Interface
	ns     string
}

// newPreBackupPods returns a PreBackupPods
func newPreBackupPods(c *AppuioV1alpha1Client, namespace string) *preBackupPods {
	return &preBackupPods{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the preBackupPod, and returns the corresponding preBackupPod object, and an error if there is any.
func (c *preBackupPods) Get(name string, options v1.GetOptions) (result *v1alpha1.PreBackupPod, err error) {
	result = &v1alpha1.PreBackupPod{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("prebackuppods").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of PreBackupPods that match those selectors.
func (c *preBackupPods) List(opts v1.ListOptions) (result *v1alpha1.PreBackupPodList, err error) {
	result = &v1alpha1.PreBackupPodList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("prebackuppods").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested preBackupPods.
func (c *preBackupPods) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("prebackuppods").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a preBackupPod and creates it.  Returns the server's representation of the preBackupPod, and an error, if there is any.
func (c *preBackupPods) Create(preBackupPod *v1alpha1.PreBackupPod) (result *v1alpha1.PreBackupPod, err error) {
	result = &v1alpha1.PreBackupPod{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("prebackuppods").
		Body(preBackupPod).
		Do().
		Into(result)
	return
}

// Update takes the representation of a preBackupPod and updates it. Returns the server's representation of the preBackupPod, and an error, if there is any.
func (c *preBackupPods) Update(preBackupPod *v1alpha1.PreBackupPod) (result *v1alpha1.PreBackupPod, err error) {
	result = &v1alpha1.PreBackupPod{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("prebackuppods").
		Name(preBackupPod.Name).
		Body(preBackupPod).
		Do().
		Into(result)
	return
}

// Delete takes name of the preBackupPod and deletes it. Returns an error if one occurs.
func (c *preBackupPods) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("prebackuppods").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *preBackupPods) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("prebackuppods").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched preBackupPod.
func (c *preBackupPods) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.PreBackupPod, err error) {
	result = &v1alpha1.PreBackupPod{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("prebackuppods").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
