/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "git.vshn.net/vshn/baas/apis/backup/v1alpha1"
	scheme "git.vshn.net/vshn/baas/client/k8s/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// PrunesGetter has a method to return a PruneInterface.
// A group's client should implement this interface.
type PrunesGetter interface {
	Prunes(namespace string) PruneInterface
}

// PruneInterface has methods to work with Prune resources.
type PruneInterface interface {
	Create(*v1alpha1.Prune) (*v1alpha1.Prune, error)
	Update(*v1alpha1.Prune) (*v1alpha1.Prune, error)
	UpdateStatus(*v1alpha1.Prune) (*v1alpha1.Prune, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.Prune, error)
	List(opts v1.ListOptions) (*v1alpha1.PruneList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Prune, err error)
	PruneExpansion
}

// prunes implements PruneInterface
type prunes struct {
	client rest.Interface
	ns     string
}

// newPrunes returns a Prunes
func newPrunes(c *AppuioV1alpha1Client, namespace string) *prunes {
	return &prunes{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the prune, and returns the corresponding prune object, and an error if there is any.
func (c *prunes) Get(name string, options v1.GetOptions) (result *v1alpha1.Prune, err error) {
	result = &v1alpha1.Prune{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("prunes").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Prunes that match those selectors.
func (c *prunes) List(opts v1.ListOptions) (result *v1alpha1.PruneList, err error) {
	result = &v1alpha1.PruneList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("prunes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested prunes.
func (c *prunes) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("prunes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a prune and creates it.  Returns the server's representation of the prune, and an error, if there is any.
func (c *prunes) Create(prune *v1alpha1.Prune) (result *v1alpha1.Prune, err error) {
	result = &v1alpha1.Prune{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("prunes").
		Body(prune).
		Do().
		Into(result)
	return
}

// Update takes the representation of a prune and updates it. Returns the server's representation of the prune, and an error, if there is any.
func (c *prunes) Update(prune *v1alpha1.Prune) (result *v1alpha1.Prune, err error) {
	result = &v1alpha1.Prune{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("prunes").
		Name(prune.Name).
		Body(prune).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *prunes) UpdateStatus(prune *v1alpha1.Prune) (result *v1alpha1.Prune, err error) {
	result = &v1alpha1.Prune{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("prunes").
		Name(prune.Name).
		SubResource("status").
		Body(prune).
		Do().
		Into(result)
	return
}

// Delete takes name of the prune and deletes it. Returns an error if one occurs.
func (c *prunes) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("prunes").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *prunes) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("prunes").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched prune.
func (c *prunes) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Prune, err error) {
	result = &v1alpha1.Prune{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("prunes").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
