= Restic Configuration Reference

For users, `k8up restic` can only be configured through the respective xref:references/object-specifications.adoc[Custom Resources `Schedule`, `Backup`, `Check`, `Prune`, `Archive` and `Restore`] and through xref:references/operator-config-reference.adoc[the _global_ properties of the `k8up operator`].

[NOTE]
  The `k8up restic` module used to be a component called _wrestic_.
  Their repositories were merged in 2021.

== Arguments and Environment Variables

The required arguments depend on the actions that should be performed.

* The environment variable `RESTIC_PASSWORD` must always be defined.
  It is not used by `k8up restic` directly, but it is used when the actual `restic` binary is invoked.
* The argument `--resticRepository` must always be defined.
* If `--prune` is set, then all the `--keepWithin*` arguments need to be valid and positive durations, https://pkg.go.dev/time#ParseDuration[see the respective Go documentation].
* If `--prune` is set, then all the other `--keep*` arguments (except `--keepTags`) need to be positive numbers (integers).
* If `--restore` is set, then `--restoreType` must be defined as well.
* If `--restore` is set and `--restoreType` is set to `s3`, then all the `--restoreS3*` arguments have to be defined as well.

See `k8up restic --help` for all the options:

[source,txt]
----
include::example$usage/restic.txt[]
----
