= How to Install K8up

== Helm

The most convenient way to install K8up on your Kubernetes cluster is by using https://helm.sh/[helm].

Please refer to the separate installation instructions in the https://github.com/k8up-io/k8up/tree/master/charts/k8up[Helm chart].

== Command-Line Tool (CLI)

The command-line tool can be downloaded from the https://github.com/k8up-io/k8up/releases["Releases" page on GitHub], and installed in your `$PATH`.

After installation, run the `k8up --version` command to make sure it is properly installed.

=== Shell Completion

The K8up CLI supports basic bash completion for subcommands.
To enable it, add the following to your `~/.bashrc`:

[source,bash]
----
_k8up_complete() {
    local cur
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    COMPREPLY=( $(compgen -W "$(k8up --generate-bash-completion)" -- "${cur}") )
    return 0
}
complete -F _k8up_complete k8up
----

NOTE: This provides completion for subcommands (`operator`, `restic`, `cli`). Flag completion is not supported by the underlying CLI framework (urfave/cli v2).

== Samples

You can find some examples of use of K8up in the `config/samples/` folder of the K8up repository:

[source,bash]
----
kubectl apply -k config/samples/
----

Please be aware that these manifests are intended for testing, development, and as examples.
