= How to Optimize schedules across the cluster

K8up features advanced scheduling mechanisms that allow you to optimize backup and other schedules.

When you start having hundreds of backup, check, prune or archive schedules it can become a bad idea to run them all at the same time.
However, manually trying to balance the schedules to different times is no solution either.

Enter smart schedules.
In addition to the standard Cron syntax (for example `* */12 * * *`) K8up features stable randomization of schedules.
Enter a special `-random`-suffixed schedule to your spec in order to let K8up generate a schedule for you.

A schedule of `@weekly-random` generates an effective schedule like `52 4 * * 4`.

TIP: The full specification of the schedules can be found in the xref:references/schedule-specification.adoc[Schedule Specifications]

The generated schedules are randomized with a stable seed based on the namespace and name of the schedule object.
That means that every schedule object will have different schedules, but deleting and recreating the same schedule will have the same effective schedules.
This behaviour allows portability between clusters.
