apiVersion: k8up.io/v1
kind: Backup
metadata:
  name: k8up-backup
  namespace: k8up-e2e-subject
spec:
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  backend:
    repoPasswordSecretRef:
      name: backup-repo
      key: password
    s3:
      endpoint: http://minio.minio.svc.cluster.local:9000
      bucket: backup
      region:
      accessKeyIDSecretRef:
        name: backup-credentials
        key: username
      secretAccessKeySecretRef:
        name: backup-credentials
        key: password
  podSecurityContext:
    runAsUser: $ID
