/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/vshn/k8up/apis/backup/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePrunes implements PruneInterface
type FakePrunes struct {
	Fake *FakeAppuioV1alpha1
	ns   string
}

var prunesResource = schema.GroupVersionResource{Group: "appuio.ch", Version: "v1alpha1", Resource: "prunes"}

var prunesKind = schema.GroupVersionKind{Group: "appuio.ch", Version: "v1alpha1", Kind: "Prune"}

// Get takes name of the prune, and returns the corresponding prune object, and an error if there is any.
func (c *FakePrunes) Get(name string, options v1.GetOptions) (result *v1alpha1.Prune, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(prunesResource, c.ns, name), &v1alpha1.Prune{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Prune), err
}

// List takes label and field selectors, and returns the list of Prunes that match those selectors.
func (c *FakePrunes) List(opts v1.ListOptions) (result *v1alpha1.PruneList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(prunesResource, prunesKind, c.ns, opts), &v1alpha1.PruneList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.PruneList{ListMeta: obj.(*v1alpha1.PruneList).ListMeta}
	for _, item := range obj.(*v1alpha1.PruneList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested prunes.
func (c *FakePrunes) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(prunesResource, c.ns, opts))

}

// Create takes the representation of a prune and creates it.  Returns the server's representation of the prune, and an error, if there is any.
func (c *FakePrunes) Create(prune *v1alpha1.Prune) (result *v1alpha1.Prune, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(prunesResource, c.ns, prune), &v1alpha1.Prune{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Prune), err
}

// Update takes the representation of a prune and updates it. Returns the server's representation of the prune, and an error, if there is any.
func (c *FakePrunes) Update(prune *v1alpha1.Prune) (result *v1alpha1.Prune, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(prunesResource, c.ns, prune), &v1alpha1.Prune{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Prune), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakePrunes) UpdateStatus(prune *v1alpha1.Prune) (*v1alpha1.Prune, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(prunesResource, "status", c.ns, prune), &v1alpha1.Prune{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Prune), err
}

// Delete takes name of the prune and deletes it. Returns an error if one occurs.
func (c *FakePrunes) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(prunesResource, c.ns, name), &v1alpha1.Prune{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePrunes) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(prunesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.PruneList{})
	return err
}

// Patch applies the patch and returns the patched prune.
func (c *FakePrunes) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Prune, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(prunesResource, c.ns, name, data, subresources...), &v1alpha1.Prune{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Prune), err
}
