/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/vshn/k8up/apis/backup/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePreBackupPods implements PreBackupPodInterface
type FakePreBackupPods struct {
	Fake *FakeAppuioV1alpha1
	ns   string
}

var prebackuppodsResource = schema.GroupVersionResource{Group: "appuio.ch", Version: "v1alpha1", Resource: "prebackuppods"}

var prebackuppodsKind = schema.GroupVersionKind{Group: "appuio.ch", Version: "v1alpha1", Kind: "PreBackupPod"}

// Get takes name of the preBackupPod, and returns the corresponding preBackupPod object, and an error if there is any.
func (c *FakePreBackupPods) Get(name string, options v1.GetOptions) (result *v1alpha1.PreBackupPod, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(prebackuppodsResource, c.ns, name), &v1alpha1.PreBackupPod{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PreBackupPod), err
}

// List takes label and field selectors, and returns the list of PreBackupPods that match those selectors.
func (c *FakePreBackupPods) List(opts v1.ListOptions) (result *v1alpha1.PreBackupPodList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(prebackuppodsResource, prebackuppodsKind, c.ns, opts), &v1alpha1.PreBackupPodList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.PreBackupPodList{ListMeta: obj.(*v1alpha1.PreBackupPodList).ListMeta}
	for _, item := range obj.(*v1alpha1.PreBackupPodList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested preBackupPods.
func (c *FakePreBackupPods) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(prebackuppodsResource, c.ns, opts))

}

// Create takes the representation of a preBackupPod and creates it.  Returns the server's representation of the preBackupPod, and an error, if there is any.
func (c *FakePreBackupPods) Create(preBackupPod *v1alpha1.PreBackupPod) (result *v1alpha1.PreBackupPod, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(prebackuppodsResource, c.ns, preBackupPod), &v1alpha1.PreBackupPod{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PreBackupPod), err
}

// Update takes the representation of a preBackupPod and updates it. Returns the server's representation of the preBackupPod, and an error, if there is any.
func (c *FakePreBackupPods) Update(preBackupPod *v1alpha1.PreBackupPod) (result *v1alpha1.PreBackupPod, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(prebackuppodsResource, c.ns, preBackupPod), &v1alpha1.PreBackupPod{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PreBackupPod), err
}

// Delete takes name of the preBackupPod and deletes it. Returns an error if one occurs.
func (c *FakePreBackupPods) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(prebackuppodsResource, c.ns, name), &v1alpha1.PreBackupPod{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePreBackupPods) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(prebackuppodsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.PreBackupPodList{})
	return err
}

// Patch applies the patch and returns the patched preBackupPod.
func (c *FakePreBackupPods) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.PreBackupPod, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(prebackuppodsResource, c.ns, name, data, subresources...), &v1alpha1.PreBackupPod{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PreBackupPod), err
}
