/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "git.vshn.net/vshn/baas/apis/backup/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeArchives implements ArchiveInterface
type FakeArchives struct {
	Fake *FakeAppuioV1alpha1
	ns   string
}

var archivesResource = schema.GroupVersionResource{Group: "appuio.ch", Version: "v1alpha1", Resource: "archives"}

var archivesKind = schema.GroupVersionKind{Group: "appuio.ch", Version: "v1alpha1", Kind: "Archive"}

// Get takes name of the archive, and returns the corresponding archive object, and an error if there is any.
func (c *FakeArchives) Get(name string, options v1.GetOptions) (result *v1alpha1.Archive, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(archivesResource, c.ns, name), &v1alpha1.Archive{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Archive), err
}

// List takes label and field selectors, and returns the list of Archives that match those selectors.
func (c *FakeArchives) List(opts v1.ListOptions) (result *v1alpha1.ArchiveList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(archivesResource, archivesKind, c.ns, opts), &v1alpha1.ArchiveList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ArchiveList{ListMeta: obj.(*v1alpha1.ArchiveList).ListMeta}
	for _, item := range obj.(*v1alpha1.ArchiveList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested archives.
func (c *FakeArchives) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(archivesResource, c.ns, opts))

}

// Create takes the representation of a archive and creates it.  Returns the server's representation of the archive, and an error, if there is any.
func (c *FakeArchives) Create(archive *v1alpha1.Archive) (result *v1alpha1.Archive, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(archivesResource, c.ns, archive), &v1alpha1.Archive{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Archive), err
}

// Update takes the representation of a archive and updates it. Returns the server's representation of the archive, and an error, if there is any.
func (c *FakeArchives) Update(archive *v1alpha1.Archive) (result *v1alpha1.Archive, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(archivesResource, c.ns, archive), &v1alpha1.Archive{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Archive), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeArchives) UpdateStatus(archive *v1alpha1.Archive) (*v1alpha1.Archive, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(archivesResource, "status", c.ns, archive), &v1alpha1.Archive{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Archive), err
}

// Delete takes name of the archive and deletes it. Returns an error if one occurs.
func (c *FakeArchives) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(archivesResource, c.ns, name), &v1alpha1.Archive{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeArchives) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(archivesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.ArchiveList{})
	return err
}

// Patch applies the patch and returns the patched archive.
func (c *FakeArchives) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Archive, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(archivesResource, c.ns, name, data, subresources...), &v1alpha1.Archive{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Archive), err
}
