{{- if .Values.rbac.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: '{{ include "k8up.fullname" . }}-executor'
  labels:
    {{- include "k8up.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create
  - apiGroups:
      - k8up.io
    resources:
      - snapshots
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
{{- end -}}
