name: ChartTest

on:
  pull_request:
    # only run when there are chart changes
    paths:
      - 'charts/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          fetch-depth: '0'

      - name: Determine Go version from go.mod
        run: echo "GO_VERSION=$(go mod edit -json | jq -r .Go)" >> $GITHUB_ENV
        working-directory: ./charts

      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c
        with:
          go-version: ${{ env.GO_VERSION }}


      - name: Run chart tests
        run: make chart-test
