name: Lint

on:
  pull_request: {}
  push:
    branches:
    - master
env:
  GOTOOLCHAIN: 'auto'


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7

    - uses: actions/setup-go@v6

    - name: Run linters
      run: make lint
