name: Release

on:
  push:
    tags:
    - "v*"

jobs:
  dist:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to publish a release
      packages: write # Required to push the docker images
      id-token: write # Required for Cosign Keyless OIDC flow

    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      with:
        fetch-depth: 0

    - name: Determine Go version from go.mod
      run: echo "GO_VERSION=$(go mod edit -json | jq -r .Go)" >> $GITHUB_ENV

    - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Install Cosign
      uses: sigstore/cosign-installer@7e8b541eb2e61bf99390e1afd4be13a184e9ebc5

    - name: Check Cosign installation
      run: cosign version

    - name: Set up QEMU
      uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5


    - name: Login to quay.io
      uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_IO_USERNAME }}
        password: ${{ secrets.QUAY_IO_PASSWORD }}

    - name: Login to GHCR
      uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build changelog from PRs with labels
      id: build_changelog
      uses: mikepenz/release-changelog-builder-action@c9bcd8238b6f41e05561348339429d360b1c0247
      with:
        configuration: ".github/changelog-configuration.json"
        # PreReleases still get a changelog, but the next full release gets a diff since the last full release,
        # combining possible changelogs of all previous PreReleases in between. PreReleases show a partial changelog
        # since last PreRelease.
        ignorePreReleases: "${{ !contains(github.ref, '-rc') }}"
        outputFile: .github/release-notes.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish releases
      uses: goreleaser/goreleaser-action@5daf1e915a5f0af01ddbcd89a43b8061ff4f1a89
      with:
        args: release --release-notes .github/release-notes.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Verify ghcr.io image signature
      run: |
        cosign verify ghcr.io/${{ github.repository }}:${{ github.ref_name }} \
          --certificate-identity "https://github.com/${{ github.workflow_ref }}" \
          --certificate-oidc-issuer "https://token.actions.githubusercontent.com"

    - name: Verify quay.io image signature
      run: |
        cosign verify quay.io/${{ github.repository }}:${{ github.ref_name }} \
          --certificate-identity "https://github.com/${{ github.workflow_ref }}" \
          --certificate-oidc-issuer "https://token.actions.githubusercontent.com"
