name: Test

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - charts/**
      - docs/**
  push:
    branches:
      - master
    paths-ignore:
      - charts/**
      - docs/**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10

    - name: Determine Go version from go.mod
      run: echo "GO_VERSION=$(go mod edit -json | jq -r .Go)" >> $GITHUB_ENV

    - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c
      with:
        go-version: ${{ env.GO_VERSION }}


    - name: Run tests
      run: make test

    - name: Run integration tests
      run: make integration-test
